apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watson-nlp-watson-nlp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: watson-nlp
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/watson-nlp/watson-nlp
    repoURL: https://github.com/dptiwari-ibm/watson-nlp.git
    targetRevision: main
    helm:
      releaseName: watson-nlp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
