apiVersion: v1
kind: Namespace
metadata:
  name: watson-nlp
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: watson-nlp-operator-group
  namespace: watson-nlp
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - watson-nlp
---
