apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watson-nlp-ubi-helm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: watson-nlp
    server: https://kubernetes.default.svc
  project: 3-applications
  source:
    path: payload/3-applications/namespace/watson-nlp/ubi-helm
    repoURL: https://github.com/dptiwari-ibm/watson-nlp.git
    targetRevision: main
    helm:
      releaseName: ubi-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
