apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-wawtson-nlp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/wawtson-nlp/namespace
    repoURL: https://github.com/dptiwari-ibm/watson-nlp.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
