apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wawtson-nlp-artifactory-key
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wawtson-nlp
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/wawtson-nlp/artifactory-key
    repoURL: https://github.com/dptiwari-ibm/watson-nlp.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
