apiVersion: v1
kind: Namespace
metadata:
  name: wawtson-nlp
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: wawtson-nlp-operator-group
  namespace: wawtson-nlp
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - wawtson-nlp
---
